apiVersion: v1
kind: Service
metadata:
  name: {{ include "dendrite.fullname" . }}
  labels:
    {{- include "dendrite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: dendrite
      protocol: TCP 
  selector:
    {{- include "dendrite.selectorLabels" . | nindent 4 }}
