apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "conduit.fullname" . }}-config
data:
  conduit.toml: |
    [global]
    server_name = "{{ .Values.domain }}"
    database_path = "/var/lib/matrix-conduit/"
    database_backend = "rocksdb"
    port = 6167
    max_request_size = {{ .Values.maxUploadSizeBytes }}
    allow_registration = {{ .Values.registration.enabled }}
    allow_federation = {{ .Values.federation.enabled }}
    trusted_servers = ["matrix.org"]
    {{- if ne .Values.maxConcurrentRequests -1 }}
    max_concurrent_requests = 100
    {{- end }}
    log = "info,state_res=warn,rocket=off,_=off,sled=off"
    address = "0.0.0.0"
